# Allow auth-service ingress from anywhere
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-auth-ingress
  namespace: portal-prod
spec:
  podSelector:
    matchLabels:
      app: auth-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3001
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
      ports:
        - port: 5432
        - port: 6379
---
# Allow result-service
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-result-ingress
  namespace: portal-prod
spec:
  podSelector:
    matchLabels:
      app: result-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3002
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
      ports:
        - port: 5432
---
# Allow grade-service
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grade-ingress
  namespace: portal-prod
spec:
  podSelector:
    matchLabels:
      app: grade-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3003
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
      ports:
        - port: 5432
---
# Allow admin-service
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-admin-ingress
  namespace: portal-prod
spec:
  podSelector:
    matchLabels:
      app: admin-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 3004
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
      ports:
        - port: 5432
