sonar.projectKey=securegarde-grade
sonar.projectName=SecureGrade Grade Service
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=node_modules/**,**/*.test.js
sonar.host.url=http://localhost:9000
sonar.token=sqa_1bfada531c768e96a0913d0183091147de89e9f5
