apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-service
  namespace: portal-prod
  labels:
    app: grade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-service
  template:
    metadata:
      labels:
        app: grade-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: grade-service
          image: securegarde-grade-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: PORT
              value: "3003"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_PUBLIC_KEY
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: tmp
          emptyDir: {}
