apiVersion: v1
kind: Service
metadata:
  name: grade-service
  namespace: portal-prod
spec:
  selector:
    app: grade-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP

