apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: portal-prod
spec:
  selector:
    app: result-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
